### ISSUE TITLE
Does not work on 3.65 Testkit firmware (converted from retail using CEX2REX)

### ISSUE THREAD

**Issue by Resident007** [Ibrahim778/USBDisable#5]
As far as my research has progressed, the NID of SceShell for 3.65 PTEL firmware is 0x587F9CED. I added it into main.c as follows:

```
switch (modinfo.module_nid)
        {
            case 0x0552F692: // 3.60 retail
                hook = taiHookFunctionOffset(&ref, modinfo.modid, 0, 0x1c9bfa, 1, USBDisable_Patch); 
                break;

            case 0x587F9CED: // 3.65 testkit, this one is the new line I added
            case 0x5549BF1F: // 3.65 retail
            case 0x34B4D82E: // 3.67 retail
            case 0x12DAC0F3: // 3.68 retail
            case 0x0703C828: // 3.69 retail
            case 0x2053B5A5: // 3.70 retail
            case 0xF476E785: // 3.71 retail
            case 0x939FFBE9: // 3.72 retail
            case 0x734D476A: // 3.73 retail
                hook = taiHookFunctionOffset(&ref, modinfo.modid, 0, 0x1c9cc2, 1, USBDisable_Patch); 
                break;
        }
```
However, after I compiled and installed it, it still didn't work, leading me to a thought that a custom offset is needed to make it work on this firmware. Is there any hope it will be fixed or at least can I have some directions on how to get the required offset considering the fact that I'm new to C/C++ and pretty new to Vita development?

**Comment by Ibrahim778** [comment]
You'll need a bit of experience reverse engineering, Use ghidra to decompile the shell.self file of your fw version and look for the same function that we're hooking above. So you'll need to decompile the shell.self of one of the fw's that have already been reversed. 
So you'll find a function that looks exactly like the one from say, 3.60 retail, in your versions shell and find the offset.

**Comment by Resident007** [comment]
Thank you, it worked like a charm! I created a Pull Request so that you can merge it into the master branch and update the binary if you wish.

**Comment by BenMitnicK** [comment]
> Thank you, it worked like a charm! I created a Pull Request so that you can merge it into the master branch and update the binary if you wish.

Can you help me for reversing shell.self ?? I tried this https://forum.devchroma.nl/index.php?topic=88.0 but out of date vitaloader not loaded some errors. Have you a tuto ?
