### ISSUE TITLE
PSVita 1000 and 2000 don't work

### ISSUE THREAD

**Issue by BenMitnicK** [Ibrahim778/USBDisable#8]
I install under *main and reboot but not working with my 2 Vita Strange I don't know why

**Comment by Ibrahim778** [comment]
What's your FW version? 
Double check it's in the right path

**Comment by BenMitnicK** [comment]
my 2 firmware is 3.60 and installed under *main

**Comment by Ibrahim778** [comment]
Double check your file path in the config, make sure you're using the newest version

**Comment by BenMitnicK** [comment]
USBDisable V3.02 installed under *main at the first place

```
# henkaku.skprx is hard-coded to load and is not listed here
*main
ur0:tai/henkaku.suprx
ur0:tai/PluginsU/USBDisable.suprx
ur0:tai/PluginsU/QuickMenuReborn.suprx
ur0:tai/PluginsU/custom_warning.suprx
ur0:tai/PluginsU/shellsecbat.suprx
ur0:tai/PluginsU/download_enabler.suprx
#ur0:tai/PluginsU/nolockscreen.suprx
ur0:tai/PluginsU/pngshot.suprx
ur0:tai/PluginsU/fruitpeel.suprx
ur0:tai/PluginsU/PasteUnlock.suprx
ur0:tai/PluginsU/quickmenuplus.suprx
ur0:tai/PluginsU/PSVshellPlus_Shell.suprx
```

**Comment by Ibrahim778** [comment]
Check your boot logs to see if [this](https://github.com/Ibrahim778/USBDisable/blob/d32579f6b4fad979602a2c92b52b7cbd0af9f1b4/src/main.c#L55) log is output

Also confirm that you're on retail fw? Have you done something like CEX2REX or CEX2DEX?

**Comment by BenMitnicK** [comment]
I couldn't find a boot log, I don't know where it is. No, none of that, just VitaRW to have the debugging utility

**Comment by Ibrahim778** [comment]
By boot log I meant to look at your printf logs with something like Cat(a)log or PSMLogUSB
If you're truly on plain CEX 3.60 fw and you really do have it set up properly then it should be working fine.

**Comment by BenMitnicK** [comment]
> By boot log I meant to look at your printf logs with something like Cat(a)log or PSMLogUSB If you're truly on plain CEX 3.60 fw and you really do have it set up properly then it should be working fine.

yes you are right I installed a modified shell so I am no longer in CEX... I will try to see if I can find the offset

**Comment by BenMitnicK** [comment]
I tried for find offset ... I decrypted shell but I have some problems ... I have several SceShell which one to choose ?? And what function should I look for ?
